exports.pairs = {
    XBT: 'XXBTZUSD',
    ETH: 'XETHZUSD',
    REP: 'XREPZUSD',
    BAT: 'BATUSD',
    BCH: 'BCHUSD',
    ADA: 'ADAUSD',
    ATOM: 'ATOMUSD',
    DASH: 'DASHUSD',
    EOS: 'EOSUSD',
    ETC: 'XETCZUSD',
    GNO: 'GNOUSD',
    ICX: 'ICXUSD',
    LTC: 'XLTCZUSD',
    XMR: 'XXMRZUSD',
    QTUM: 'QTUMUSD',
    XRP: 'XXRPZUSD',
    XLM: 'XXLMZUSD',
    USDT: 'USDTZUSD',
    XTZ: 'XTZUSD',
    WAVES: 'WAVESUSD',
    ZEC: 'XZECZUSD'
};

exports.coinname = {
    XBT: 'Bitcoin',
    ETH: 'Ethereum',
    REP: 'Augur',
    BAT: 'Brave Attention Token',
    BCH: 'Bitcoin Cash',
    ADA: 'Cordano',
    ATOM: 'Cosmos',
    DASH: 'Dash',
    EOS: 'EOS',
    ETC: 'Ethereum Classic',
    GNO: 'Gnosis',
    ICX: 'Icon',
    LTC: 'Litecoin',
    XMR: 'Monero',
    QTUM: 'Qtum',
    XRP: 'Ripple',
    XLM: 'Stellar Lumen',
    USDT: 'Tether',
    XTZ: 'Tezos',
    WAVES: 'Waves',
    ZEC: 'Zcash'
};

exports.bypair = {
    XXBTZUSD: 'XBT/USD',
    XETHZUSD: 'ETH/USD',
    XREPZUSD: 'REP/USD',
    BATUSD: 'BAT/USD',
    BCHUSD: 'BCH/USD',
    ADAUSD: 'ADA/USD',
    ATOMUSD: 'ATOM/USD',
    DASHUSD: 'DASH/USD',
    EOSUSD: 'EOS/USD',
    XETCZUSD: 'ETC/USD',
    GNOUSD: 'GNO/USD',
    ICXUSD: 'ICX/USD',
    XLTCZUSD: 'LTC/USD',
    XXMRZUSD: 'XMR/USD',
    QTUMUSD: 'QTUM/USD',
    XXRPZUSD: 'XRP/USD',
    XXLMZUSD: 'XLM/USD',
    USDTZUSD: 'USDT/USD',
    XTZUSD: 'XTZ/USD',
    WAVESUSD: 'WAVES/USD',
    XZECZUSD: 'ZEC/USD'
};